[2024-05-12 11:44:13] 


[2024-05-12 11:44:13] Started the Error Log File
[2024-05-12 11:44:15] No errors occurred
[2024-05-12 11:44:15] Closed the Error Log File




[2024-05-12 11:44:23] 


[2024-05-12 11:44:23] Started the Error Log File
[2024-05-12 11:44:24] No errors occurred
[2024-05-12 11:44:24] Closed the Error Log File




[2024-05-12 11:45:07] 


[2024-05-12 11:45:07] Started the Error Log File
[2024-05-12 11:45:08] No errors occurred
[2024-05-12 11:45:08] Closed the Error Log File




[2024-05-12 11:46:17] 


[2024-05-12 11:46:17] Started the Error Log File
[2024-05-12 11:46:33] No errors occurred
[2024-05-12 11:46:33] Closed the Error Log File




[2024-05-12 11:48:20] 


[2024-05-12 11:48:20] Started the Error Log File
[2024-05-12 11:51:44] 


[2024-05-12 11:51:44] Started the Error Log File
[2024-05-12 11:52:52] 


[2024-05-12 11:52:52] Started the Error Log File
[2024-05-12 11:53:07] No errors occurred
[2024-05-12 11:53:07] Closed the Error Log File




[2024-05-12 12:59:37] 


[2024-05-12 12:59:37] Started the Error Log File
[2024-05-12 12:59:38] No errors occurred
[2024-05-12 12:59:38] Closed the Error Log File




[2024-05-12 13:05:21] 


[2024-05-12 13:05:21] Started the Error Log File
[2024-05-12 13:05:22] No errors occurred
[2024-05-12 13:05:22] Closed the Error Log File




[2024-05-12 13:06:28] 


[2024-05-12 13:06:28] Started the Error Log File
[2024-05-12 13:06:29] No errors occurred
[2024-05-12 13:06:29] Closed the Error Log File




[2024-05-12 13:07:18] 


[2024-05-12 13:07:18] Started the Error Log File
[2024-05-12 13:07:19] No errors occurred
[2024-05-12 13:07:19] Closed the Error Log File




[2024-05-12 13:08:04] 


[2024-05-12 13:08:04] Started the Error Log File
[2024-05-12 13:08:05] No errors occurred
[2024-05-12 13:08:05] Closed the Error Log File




[2024-05-12 13:09:16] 


[2024-05-12 13:09:16] Started the Error Log File
[2024-05-12 13:09:18] No errors occurred
[2024-05-12 13:09:18] Closed the Error Log File




[2024-05-12 13:11:27] 


[2024-05-12 13:11:27] Started the Error Log File
[2024-05-12 13:11:28] No errors occurred
[2024-05-12 13:11:28] Closed the Error Log File




[2024-05-12 13:12:45] 


[2024-05-12 13:12:45] Started the Error Log File
[2024-05-12 13:12:46] No errors occurred
[2024-05-12 13:12:46] Closed the Error Log File




[2024-05-12 13:17:48] 


[2024-05-12 13:17:48] Started the Error Log File
[2024-05-12 13:17:49] No errors occurred
[2024-05-12 13:17:49] Closed the Error Log File




[2024-05-12 13:31:52] 


[2024-05-12 13:31:52] Started the Error Log File
[2024-05-12 13:31:53] No errors occurred
[2024-05-12 13:31:53] Closed the Error Log File




[2024-05-12 13:32:40] 


[2024-05-12 13:32:40] Started the Error Log File
[2024-05-12 13:33:10] No errors occurred
[2024-05-12 13:33:10] Closed the Error Log File




[2024-05-12 13:39:14] 


[2024-05-12 13:39:14] Started the Error Log File
[2024-05-12 13:39:21] No errors occurred
[2024-05-12 13:39:21] Closed the Error Log File




[2024-05-12 13:39:53] 


[2024-05-12 13:39:53] Started the Error Log File
[2024-05-12 13:39:54] No errors occurred
[2024-05-12 13:39:54] Closed the Error Log File




[2024-05-12 13:52:19] 


[2024-05-12 13:52:19] Started the Error Log File
[2024-05-12 13:53:53] 


[2024-05-12 13:53:53] Started the Error Log File
[2024-05-12 13:54:14] 


[2024-05-12 13:54:14] Started the Error Log File
[2024-05-12 13:54:14] No errors occurred
[2024-05-12 13:54:14] Closed the Error Log File




[2024-05-12 13:54:31] 


[2024-05-12 13:54:31] Started the Error Log File
[2024-05-12 13:58:45] 


[2024-05-12 13:58:45] Started the Error Log File
[2024-05-12 13:58:46] No errors occurred
[2024-05-12 13:58:46] Closed the Error Log File




[2024-05-12 13:59:05] 


[2024-05-12 13:59:05] Started the Error Log File
[2024-05-12 13:59:06] No errors occurred
[2024-05-12 13:59:06] Closed the Error Log File




[2024-05-12 14:00:11] 


[2024-05-12 14:00:11] Started the Error Log File
[2024-05-12 14:00:25] No errors occurred
[2024-05-12 14:00:25] Closed the Error Log File




[2024-05-12 14:14:32] 


[2024-05-12 14:14:32] Started the Error Log File
[2024-05-12 14:14:35] No errors occurred
[2024-05-12 14:14:35] Closed the Error Log File




[2024-05-12 14:14:49] 


[2024-05-12 14:14:49] Started the Error Log File
[2024-05-12 14:15:27] No errors occurred
[2024-05-12 14:15:27] Closed the Error Log File




[2024-05-12 16:26:56] 


[2024-05-12 16:26:56] Started the Error Log File
[2024-05-12 16:27:48] No errors occurred
[2024-05-12 16:27:48] Closed the Error Log File




[2024-05-12 16:27:50] 


[2024-05-12 16:27:50] Started the Error Log File
[2024-05-12 16:27:57] No errors occurred
[2024-05-12 16:27:57] Closed the Error Log File




[2024-05-12 16:30:38] 


[2024-05-12 16:30:38] Started the Error Log File
[2024-05-12 16:30:48] No errors occurred
[2024-05-12 16:30:48] Closed the Error Log File




[2024-05-12 16:33:21] 


[2024-05-12 16:33:21] Started the Error Log File
[2024-05-12 16:33:39] No errors occurred
[2024-05-12 16:33:39] Closed the Error Log File




[2024-05-12 16:33:56] 


[2024-05-12 16:33:56] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\main_snake_game.py", line 425, in patchnotes
    self.scrollable_frame = ctk.CTkScrollableFrame(self.info_canvas, bg='Grey20', highlightbackground='Black', highlightthickness=5) # pylint: disable=line-too-long
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CTkScrollableFrame.__init__() got an unexpected keyword argument 'bg'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\main_snake_game.py", line 425, in patchnotes
    self.scrollable_frame = ctk.CTkScrollableFrame(self.info_canvas, bg='Grey20', highlightbackground='Black', highlightthickness=5) # pylint: disable=line-too-long
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CTkScrollableFrame.__init__() got an unexpected keyword argument 'bg'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\main_snake_game.py", line 425, in patchnotes
    self.scrollable_frame = ctk.CTkScrollableFrame(self.info_canvas, bg='Grey20', highlightbackground='Black', highlightthickness=5) # pylint: disable=line-too-long
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CTkScrollableFrame.__init__() got an unexpected keyword argument 'bg'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\main_snake_game.py", line 425, in patchnotes
    self.scrollable_frame = ctk.CTkScrollableFrame(self.info_canvas, bg='Grey20', highlightbackground='Black', highlightthickness=5) # pylint: disable=line-too-long
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CTkScrollableFrame.__init__() got an unexpected keyword argument 'bg'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\main_snake_game.py", line 425, in patchnotes
    self.scrollable_frame = ctk.CTkScrollableFrame(self.info_canvas, bg='Grey20', highlightbackground='Black', highlightthickness=5) # pylint: disable=line-too-long
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CTkScrollableFrame.__init__() got an unexpected keyword argument 'bg'
[2024-05-12 16:34:01] No errors occurred
[2024-05-12 16:34:01] Closed the Error Log File




[2024-05-12 16:35:17] 


[2024-05-12 16:35:17] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\main_snake_game.py", line 425, in patchnotes
    self.scrollable_frame = ctk.CTkScrollableFrame(self.info_canvas, width=600, height=400, bg='Grey20')
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CTkScrollableFrame.__init__() got an unexpected keyword argument 'bg'
[2024-05-12 16:35:20] No errors occurred
[2024-05-12 16:35:20] Closed the Error Log File




[2024-05-12 16:35:33] 


[2024-05-12 16:35:33] Started the Error Log File
[2024-05-12 16:35:59] No errors occurred
[2024-05-12 16:35:59] Closed the Error Log File




[2024-05-12 16:41:56] 


[2024-05-12 16:41:56] Started the Error Log File
[2024-05-12 16:42:14] No errors occurred
[2024-05-12 16:42:14] Closed the Error Log File




[2024-05-12 16:44:00] 


[2024-05-12 16:44:00] Started the Error Log File
[2024-05-12 16:44:17] No errors occurred
[2024-05-12 16:44:17] Closed the Error Log File




[2024-05-12 16:44:26] 


[2024-05-12 16:44:26] Started the Error Log File
[2024-05-12 16:44:32] No errors occurred
[2024-05-12 16:44:32] Closed the Error Log File




[2024-05-12 16:55:40] 


[2024-05-12 16:55:40] Started the Error Log File
[2024-05-12 16:55:51] No errors occurred
[2024-05-12 16:55:51] Closed the Error Log File




[2024-05-12 16:56:01] 


[2024-05-12 16:56:01] Started the Error Log File
[2024-05-12 16:56:40] No errors occurred
[2024-05-12 16:56:40] Closed the Error Log File




[2024-05-12 16:56:59] 


[2024-05-12 16:56:59] Started the Error Log File
[2024-05-12 16:57:05] No errors occurred
[2024-05-12 16:57:05] Closed the Error Log File




[2024-05-12 16:57:12] 


[2024-05-12 16:57:12] Started the Error Log File
[2024-05-12 16:57:20] No errors occurred
[2024-05-12 16:57:20] Closed the Error Log File




[2024-05-12 16:57:38] 


[2024-05-12 16:57:38] Started the Error Log File
[2024-05-12 16:57:47] No errors occurred
[2024-05-12 16:57:47] Closed the Error Log File




[2024-05-12 16:57:56] 


[2024-05-12 16:57:56] Started the Error Log File
[2024-05-12 16:58:02] No errors occurred
[2024-05-12 16:58:02] Closed the Error Log File




[2024-05-12 16:58:23] 


[2024-05-12 16:58:23] Started the Error Log File
[2024-05-12 16:58:29] No errors occurred
[2024-05-12 16:58:29] Closed the Error Log File




[2024-05-12 16:58:38] 


[2024-05-12 16:58:38] Started the Error Log File
[2024-05-12 16:58:45] No errors occurred
[2024-05-12 16:58:45] Closed the Error Log File




[2024-05-12 16:58:54] 


[2024-05-12 16:58:54] Started the Error Log File
[2024-05-12 17:04:36] No errors occurred
[2024-05-12 17:04:36] Closed the Error Log File




[2024-05-12 17:04:38] 


[2024-05-12 17:04:38] Started the Error Log File
[2024-05-12 17:04:39] No errors occurred
[2024-05-12 17:04:39] Closed the Error Log File




[2024-05-12 17:11:57] 


[2024-05-12 17:11:57] Started the Error Log File
[2024-05-12 17:12:13] No errors occurred
[2024-05-12 17:12:13] Closed the Error Log File




[2024-05-12 17:16:55] 


[2024-05-12 17:16:55] Started the Error Log File
[2024-05-12 17:17:18] No errors occurred
[2024-05-12 17:17:18] Closed the Error Log File




[2024-05-12 17:38:41] 


[2024-05-12 17:38:41] Started the Error Log File
[2024-05-12 17:39:58] No errors occurred
[2024-05-12 17:39:58] Closed the Error Log File




[2024-05-12 17:42:27] 


[2024-05-12 17:42:27] Started the Error Log File
[2024-05-12 17:42:43] No errors occurred
[2024-05-12 17:42:43] Closed the Error Log File




[2024-05-12 17:43:21] 


[2024-05-12 17:43:21] Started the Error Log File
[2024-05-12 17:43:34] No errors occurred
[2024-05-12 17:43:34] Closed the Error Log File




[2024-05-12 17:45:26] 


[2024-05-12 17:45:26] Started the Error Log File
[2024-05-12 17:45:33] No errors occurred
[2024-05-12 17:45:33] Closed the Error Log File




[2024-05-12 19:51:15] 


[2024-05-12 19:51:15] Started the Error Log File
[2024-05-12 19:51:29] No errors occurred
[2024-05-12 19:51:29] Closed the Error Log File




[2024-05-13 18:56:20] 


[2024-05-13 18:56:20] Started the Error Log File
[2024-05-13 18:57:48] No errors occurred
[2024-05-13 18:57:48] Closed the Error Log File




[2024-05-13 18:58:36] 


[2024-05-13 18:58:36] Started the Error Log File
[2024-05-13 18:58:44] No errors occurred
[2024-05-13 18:58:44] Closed the Error Log File




[2024-05-13 18:58:53] 


[2024-05-13 18:58:53] Started the Error Log File
[2024-05-13 18:59:00] No errors occurred
[2024-05-13 18:59:00] Closed the Error Log File




[2024-05-13 18:59:05] 


[2024-05-13 18:59:05] Started the Error Log File
[2024-05-13 18:59:11] No errors occurred
[2024-05-13 18:59:11] Closed the Error Log File




[2024-05-13 18:59:20] 


[2024-05-13 18:59:20] Started the Error Log File
[2024-05-13 18:59:39] No errors occurred
[2024-05-13 18:59:39] Closed the Error Log File




[2024-05-13 19:04:04] 


[2024-05-13 19:04:04] Started the Error Log File
[2024-05-13 19:04:51] No errors occurred
[2024-05-13 19:04:51] Closed the Error Log File




[2024-05-13 19:05:42] 


[2024-05-13 19:05:42] Started the Error Log File
[2024-05-13 19:06:02] No errors occurred
[2024-05-13 19:06:02] Closed the Error Log File




[2024-05-13 19:06:08] 


[2024-05-13 19:06:08] Started the Error Log File
[2024-05-13 19:06:27] No errors occurred
[2024-05-13 19:06:27] Closed the Error Log File




[2024-05-13 19:06:30] 


[2024-05-13 19:06:30] Started the Error Log File
[2024-05-13 19:06:58] No errors occurred
[2024-05-13 19:06:58] Closed the Error Log File




[2024-05-13 19:07:03] 


[2024-05-13 19:07:03] Started the Error Log File
[2024-05-13 19:08:31] No errors occurred
[2024-05-13 19:08:31] Closed the Error Log File




[2024-05-13 19:08:54] 


[2024-05-13 19:08:54] Started the Error Log File
[2024-05-13 19:13:00] No errors occurred
[2024-05-13 19:13:00] Closed the Error Log File




[2024-05-13 19:13:35] 


[2024-05-13 19:13:35] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
[2024-05-13 19:13:42] No errors occurred
[2024-05-13 19:13:42] Closed the Error Log File




[2024-05-13 19:15:19] 


[2024-05-13 19:15:19] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text=main['date'],
         ~~~~^^^^^^^^
KeyError: 'date'
[2024-05-13 19:15:22] No errors occurred
[2024-05-13 19:15:22] Closed the Error Log File




[2024-05-13 19:20:24] 


[2024-05-13 19:20:24] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text=main['date'],
         ~~~~^^^^^^^^
KeyError: 'date'
[2024-05-13 19:20:26] No errors occurred
[2024-05-13 19:20:26] Closed the Error Log File




[2024-05-13 19:20:38] 


[2024-05-13 19:20:38] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text=main['date'],
         ~~~~^^^^^^^^
KeyError: 'date'
[2024-05-13 19:20:41] No errors occurred
[2024-05-13 19:20:41] Closed the Error Log File




[2024-05-13 19:20:48] 


[2024-05-13 19:20:48] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
[2024-05-13 19:20:53] No errors occurred
[2024-05-13 19:20:53] Closed the Error Log File




[2024-05-13 19:21:24] 


[2024-05-13 19:21:24] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
[2024-05-13 19:21:29] No errors occurred
[2024-05-13 19:21:29] Closed the Error Log File




[2024-05-13 19:22:13] 


[2024-05-13 19:22:13] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
[2024-05-13 19:22:17] No errors occurred
[2024-05-13 19:22:17] Closed the Error Log File




[2024-05-13 19:22:20] 


[2024-05-13 19:22:20] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
[2024-05-13 19:22:25] No errors occurred
[2024-05-13 19:22:25] Closed the Error Log File




[2024-05-13 19:23:00] 


[2024-05-13 19:23:00] Started the Error Log File
[2024-05-13 19:23:11] No errors occurred
[2024-05-13 19:23:11] Closed the Error Log File




[2024-05-13 19:31:08] 


[2024-05-13 19:31:08] Started the Error Log File
[2024-05-13 19:31:27] No errors occurred
[2024-05-13 19:31:27] Closed the Error Log File




[2024-05-13 19:31:30] 


[2024-05-13 19:31:30] Started the Error Log File
[2024-05-13 19:31:41] No errors occurred
[2024-05-13 19:31:41] Closed the Error Log File




[2024-05-13 19:31:48] 


[2024-05-13 19:31:48] Started the Error Log File
[2024-05-13 19:31:58] No errors occurred
[2024-05-13 19:31:58] Closed the Error Log File




[2024-05-13 19:32:06] 


[2024-05-13 19:32:06] Started the Error Log File
[2024-05-13 19:32:12] No errors occurred
[2024-05-13 19:32:12] Closed the Error Log File




[2024-05-13 19:32:19] 


[2024-05-13 19:32:19] Started the Error Log File
[2024-05-13 19:32:26] No errors occurred
[2024-05-13 19:32:26] Closed the Error Log File




[2024-05-13 19:32:44] 


[2024-05-13 19:32:44] Started the Error Log File
[2024-05-13 19:32:47] No errors occurred
[2024-05-13 19:32:47] Closed the Error Log File




[2024-05-13 19:33:03] 


[2024-05-13 19:33:03] Started the Error Log File
[2024-05-13 19:33:11] No errors occurred
[2024-05-13 19:33:11] Closed the Error Log File




[2024-05-13 19:33:18] 


[2024-05-13 19:33:18] Started the Error Log File
[2024-05-13 19:33:31] No errors occurred
[2024-05-13 19:33:31] Closed the Error Log File




[2024-05-13 19:33:56] 


[2024-05-13 19:33:56] Started the Error Log File
[2024-05-13 19:34:01] No errors occurred
[2024-05-13 19:34:01] Closed the Error Log File




[2024-05-13 19:34:05] 


[2024-05-13 19:34:05] Started the Error Log File
[2024-05-13 19:35:48] No errors occurred
[2024-05-13 19:35:48] Closed the Error Log File




[2024-05-13 19:35:51] 


[2024-05-13 19:35:51] Started the Error Log File
[2024-05-13 19:36:13] No errors occurred
[2024-05-13 19:36:13] Closed the Error Log File




[2024-05-13 19:38:43] 


[2024-05-13 19:38:43] Started the Error Log File
[2024-05-13 19:38:56] No errors occurred
[2024-05-13 19:38:56] Closed the Error Log File




[2024-05-16 19:41:53] 


[2024-05-16 19:41:53] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 82, in classic_snake_command
    self.functions['classic_snake']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 196, in classic_snake
    self.start_game("classic_snake")
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 258, in start_game
    self.classic_snake_canvas = SnakeClassicGame(self.root, self.game_config, self.game_logger, self.functions, self.create_button_panel) # pylint: disable=line-too-long
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_classic_game.py", line 97, in __init__
    self.configfile()
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_classic_game.py", line 158, in configfile
    'Up': self.config.get('KeyBindings', 'Up').split(', '),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1168, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'KeyBindings'
[2024-05-16 19:41:56] No errors occurred
[2024-05-16 19:41:56] Closed the Error Log File




[2024-05-16 19:42:20] 


[2024-05-16 19:42:20] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 805, in get
    value = d[option]
            ~^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py", line 1006, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py", line 998, in __missing__
    raise KeyError(key)
KeyError: 'pausegame'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 82, in classic_snake_command
    self.functions['classic_snake']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 196, in classic_snake
    self.start_game("classic_snake")
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 258, in start_game
    self.classic_snake_canvas = SnakeClassicGame(self.root, self.game_config, self.game_logger, self.functions, self.create_button_panel) # pylint: disable=line-too-long
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_classic_game.py", line 97, in __init__
    self.configfile()
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_classic_game.py", line 163, in configfile
    'PauseGame': self.config.get('KeyBindings', 'PauseGame').split(', '),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 808, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'pausegame' in section: 'KeyBindings'
[2024-05-16 19:42:22] No errors occurred
[2024-05-16 19:42:22] Closed the Error Log File




[2024-05-16 19:44:20] 


[2024-05-16 19:44:20] Started the Error Log File
[2024-05-16 19:44:24] No errors occurred
[2024-05-16 19:44:24] Closed the Error Log File




[2024-05-16 19:46:37] 


[2024-05-16 19:46:37] Started the Error Log File
[2024-05-16 19:46:48] No errors occurred
[2024-05-16 19:46:48] Closed the Error Log File




[2024-05-16 19:47:21] 


[2024-05-16 19:47:21] Started the Error Log File
[2024-05-16 19:47:27] No errors occurred
[2024-05-16 19:47:27] Closed the Error Log File




[2024-05-16 19:52:56] 


[2024-05-16 19:52:56] Started the Error Log File
[2024-05-16 19:53:16] No errors occurred
[2024-05-16 19:53:16] Closed the Error Log File




[2024-05-16 20:17:22] 


[2024-05-16 20:17:22] Started the Error Log File
[2024-05-16 20:18:05] No errors occurred
[2024-05-16 20:18:05] Closed the Error Log File




[2024-05-16 20:18:30] 


[2024-05-16 20:18:30] Started the Error Log File
[2024-05-16 20:18:37] No errors occurred
[2024-05-16 20:18:37] Closed the Error Log File




[2024-05-16 20:18:58] 


[2024-05-16 20:18:58] Started the Error Log File
[2024-05-16 20:19:04] No errors occurred
[2024-05-16 20:19:04] Closed the Error Log File




[2024-05-16 20:20:43] 


[2024-05-16 20:20:43] Started the Error Log File
[2024-05-16 20:20:53] No errors occurred
[2024-05-16 20:20:53] Closed the Error Log File




[2024-05-18 22:30:00] 


[2024-05-18 22:30:00] Started the Error Log File
[2024-05-18 22:30:08] No errors occurred
[2024-05-18 22:30:08] Closed the Error Log File




[2024-05-19 10:36:43] 


[2024-05-19 10:36:43] Started the Error Log File
[2024-05-19 10:37:02] No errors occurred
[2024-05-19 10:37:02] Closed the Error Log File




[2024-05-19 10:43:15] 


[2024-05-19 10:43:15] Started the Error Log File
[2024-05-19 10:43:30] No errors occurred
[2024-05-19 10:43:30] Closed the Error Log File




[2024-05-19 10:45:14] 


[2024-05-19 10:45:14] Started the Error Log File
[2024-05-19 10:45:28] No errors occurred
[2024-05-19 10:45:28] Closed the Error Log File




[2024-05-19 10:45:30] 


[2024-05-19 10:45:30] Started the Error Log File
[2024-05-19 10:45:44] No errors occurred
[2024-05-19 10:45:44] Closed the Error Log File




[2024-05-19 10:58:45] 


[2024-05-19 10:58:45] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 101, in <lambda>
    command=lambda v=value: self._button_callback(v),
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 106, in _button_callback
    self._command(value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_combobox.py", line 384, in _dropdown_callback
    self._command(value)
TypeError: OptionButtonPanel.keybindings_callback() missing 1 required positional argument: 'event'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 101, in <lambda>
    command=lambda v=value: self._button_callback(v),
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 106, in _button_callback
    self._command(value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_combobox.py", line 384, in _dropdown_callback
    self._command(value)
TypeError: OptionButtonPanel.keybindings_callback() missing 1 required positional argument: 'event'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 101, in <lambda>
    command=lambda v=value: self._button_callback(v),
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 106, in _button_callback
    self._command(value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_combobox.py", line 384, in _dropdown_callback
    self._command(value)
TypeError: OptionButtonPanel.keybindings_callback() missing 1 required positional argument: 'event'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 101, in <lambda>
    command=lambda v=value: self._button_callback(v),
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 106, in _button_callback
    self._command(value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_combobox.py", line 384, in _dropdown_callback
    self._command(value)
TypeError: OptionButtonPanel.keybindings_callback() missing 1 required positional argument: 'event'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
TypeError: OptionButtonPanel.keybindings_callback() missing 1 required positional argument: 'event'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
TypeError: OptionButtonPanel.keybindings_callback() missing 1 required positional argument: 'event'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
TypeError: OptionButtonPanel.keybindings_callback() missing 1 required positional argument: 'event'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
TypeError: OptionButtonPanel.keybindings_callback() missing 1 required positional argument: 'event'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
TypeError: OptionButtonPanel.keybindings_callback() missing 1 required positional argument: 'event'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
TypeError: OptionButtonPanel.keybindings_callback() missing 1 required positional argument: 'event'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
TypeError: OptionButtonPanel.keybindings_callback() missing 1 required positional argument: 'event'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
TypeError: OptionButtonPanel.keybindings_callback() missing 1 required positional argument: 'event'
[2024-05-19 10:59:11] No errors occurred
[2024-05-19 10:59:11] Closed the Error Log File




[2024-05-19 10:59:54] 


[2024-05-19 10:59:54] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 101, in <lambda>
    command=lambda v=value: self._button_callback(v),
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 106, in _button_callback
    self._command(value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_combobox.py", line 384, in _dropdown_callback
    self._command(value)
TypeError: OptionButtonPanel.keybindings_callback() missing 2 required positional arguments: 'event' and 'choice'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 101, in <lambda>
    command=lambda v=value: self._button_callback(v),
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 106, in _button_callback
    self._command(value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_combobox.py", line 384, in _dropdown_callback
    self._command(value)
TypeError: OptionButtonPanel.keybindings_callback() missing 2 required positional arguments: 'event' and 'choice'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 101, in <lambda>
    command=lambda v=value: self._button_callback(v),
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 106, in _button_callback
    self._command(value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_combobox.py", line 384, in _dropdown_callback
    self._command(value)
TypeError: OptionButtonPanel.keybindings_callback() missing 2 required positional arguments: 'event' and 'choice'
[2024-05-19 11:00:07] No errors occurred
[2024-05-19 11:00:07] Closed the Error Log File




[2024-05-19 11:01:53] 


[2024-05-19 11:01:53] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 101, in <lambda>
    command=lambda v=value: self._button_callback(v),
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\dropdown_menu.py", line 106, in _button_callback
    self._command(value)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_combobox.py", line 384, in _dropdown_callback
    self._command(value)
TypeError: OptionButtonPanel.keybindings_callback() missing 1 required positional argument: 'event'
[2024-05-19 11:02:01] No errors occurred
[2024-05-19 11:02:01] Closed the Error Log File




[2024-05-19 11:11:33] 


[2024-05-19 11:11:33] Started the Error Log File
[2024-05-19 11:18:37] No errors occurred
[2024-05-19 11:18:37] Closed the Error Log File




[2024-05-19 11:18:53] 


[2024-05-19 11:18:53] Started the Error Log File
[2024-05-19 11:18:57] No errors occurred
[2024-05-19 11:18:57] Closed the Error Log File




[2024-05-19 11:19:43] 


[2024-05-19 11:19:43] Started the Error Log File
[2024-05-19 11:20:22] No errors occurred
[2024-05-19 11:20:22] Closed the Error Log File




[2024-05-19 11:21:50] 


[2024-05-19 11:21:50] Started the Error Log File
[2024-05-19 11:23:14] No errors occurred
[2024-05-19 11:23:14] Closed the Error Log File




[2024-05-19 11:23:39] 


[2024-05-19 11:23:39] Started the Error Log File
[2024-05-19 11:26:56] No errors occurred
[2024-05-19 11:26:56] Closed the Error Log File




[2024-05-19 11:27:04] 


[2024-05-19 11:27:04] Started the Error Log File
[2024-05-19 11:29:46] No errors occurred
[2024-05-19 11:29:46] Closed the Error Log File




[2024-05-19 11:52:51] 


[2024-05-19 11:52:51] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 55, in settings_command
    self.functions['open_settings']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 241, in open_settings
    self.start_game("settings")
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 372, in start_game
    self.settings_labels.create_settings_labels()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 172, in create_settings_labels
    self.create_keybinding_up_label()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\labelpanel_snake_game.py", line 290, in create_keybinding_up_label
    self.keybindings_up_label = ctk.CTkLabel(self.settings_canvas,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_label.py", line 101, in __init__
    check_kwargs_empty(kwargs, raise_error=True)
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\utility\utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['corer_radius'] are not supported arguments. Look at the documentation for supported arguments.
[2024-05-19 11:52:57] No errors occurred
[2024-05-19 11:52:57] Closed the Error Log File




[2024-05-19 11:57:09] 


[2024-05-19 11:57:09] Started the Error Log File
[2024-05-19 11:57:11] No errors occurred
[2024-05-19 11:57:11] Closed the Error Log File




[2024-05-19 11:57:16] 


[2024-05-19 11:57:16] Started the Error Log File
[2024-05-19 12:40:43] No errors occurred
[2024-05-19 12:40:43] Closed the Error Log File




[2024-05-19 12:40:51] 


[2024-05-19 12:40:51] Started the Error Log File
[2024-05-19 12:41:01] No errors occurred
[2024-05-19 12:41:01] Closed the Error Log File




[2024-05-19 12:42:36] 


[2024-05-19 12:42:36] Started the Error Log File
[2024-05-19 12:43:03] No errors occurred
[2024-05-19 12:43:03] Closed the Error Log File




[2024-05-19 12:43:06] 


[2024-05-19 12:43:06] Started the Error Log File
[2024-05-19 12:43:41] No errors occurred
[2024-05-19 12:43:41] Closed the Error Log File




[2024-05-19 12:43:44] 


[2024-05-19 12:43:44] Started the Error Log File
[2024-05-19 12:57:42] No errors occurred
[2024-05-19 12:57:42] Closed the Error Log File




[2024-05-19 12:57:51] 


[2024-05-19 12:57:51] Started the Error Log File
[2024-05-19 12:58:35] No errors occurred
[2024-05-19 12:58:35] Closed the Error Log File




[2024-05-19 12:58:41] 


[2024-05-19 12:58:41] Started the Error Log File
[2024-05-19 13:01:21] No errors occurred
[2024-05-19 13:01:21] Closed the Error Log File




[2024-05-19 13:01:24] 


[2024-05-19 13:01:24] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 970, in <module>
    app = SnakeGameApp(root, GameConstants.MIN_WIDTH, GameConstants.MIN_HEIGHT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 140, in __init__
    self.create_button_panel = ClickButtonPanel(self.main_canvas, self.game_logger, self.functions) # pylint: disable=line-too-long
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 343, in __init__
    self.button_width = GameConstants.BUTTON_WIDTH
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'GameConstants' has no attribute 'BUTTON_WIDTH'
[2024-05-19 13:01:27] 


[2024-05-19 13:01:27] Started the Error Log File
Traceback (most recent call last):
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 970, in <module>
    app = SnakeGameApp(root, GameConstants.MIN_WIDTH, GameConstants.MIN_HEIGHT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 140, in __init__
    self.create_button_panel = ClickButtonPanel(self.main_canvas, self.game_logger, self.functions) # pylint: disable=line-too-long
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 343, in __init__
    self.button_width = GameConstants.BUTTON_WIDTH
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'GameConstants' has no attribute 'BUTTON_WIDTH'
[2024-05-19 13:01:58] 


[2024-05-19 13:01:58] Started the Error Log File
[2024-05-19 13:02:15] No errors occurred
[2024-05-19 13:02:15] Closed the Error Log File




[2024-05-19 13:02:35] 


[2024-05-19 13:02:35] Started the Error Log File
[2024-05-19 13:03:19] No errors occurred
[2024-05-19 13:03:19] Closed the Error Log File




[2024-05-19 13:03:27] 


[2024-05-19 13:03:27] Started the Error Log File
[2024-05-19 13:04:15] No errors occurred
[2024-05-19 13:04:15] Closed the Error Log File




[2024-05-19 13:05:56] 


[2024-05-19 13:05:56] Started the Error Log File
[2024-05-19 13:06:10] No errors occurred
[2024-05-19 13:06:10] Closed the Error Log File




[2024-05-19 13:06:13] 


[2024-05-19 13:06:13] Started the Error Log File
[2024-05-19 13:06:26] No errors occurred
[2024-05-19 13:06:26] Closed the Error Log File




[2024-05-19 13:18:34] 


[2024-05-19 13:18:34] Started the Error Log File
[2024-05-19 13:18:35] No errors occurred
[2024-05-19 13:18:35] Closed the Error Log File




[2024-05-19 13:18:38] 


[2024-05-19 13:18:38] Started the Error Log File
[2024-05-19 13:21:09] No errors occurred
[2024-05-19 13:21:09] Closed the Error Log File




[2024-05-19 13:21:11] 


[2024-05-19 13:21:11] Started the Error Log File
[2024-05-19 13:22:56] No errors occurred
[2024-05-19 13:22:56] Closed the Error Log File




[2024-05-19 13:22:59] 


[2024-05-19 13:22:59] Started the Error Log File
[2024-05-19 13:23:12] No errors occurred
[2024-05-19 13:23:12] Closed the Error Log File




[2024-05-19 13:23:42] 


[2024-05-19 13:23:42] Started the Error Log File
[2024-05-19 13:25:02] No errors occurred
[2024-05-19 13:25:02] Closed the Error Log File




[2024-05-19 13:28:29] 


[2024-05-19 13:28:29] Started the Error Log File
[2024-05-19 13:30:23] No errors occurred
[2024-05-19 13:30:23] Closed the Error Log File




[2024-05-19 13:30:26] 


[2024-05-19 13:30:26] Started the Error Log File
[2024-05-19 13:31:48] No errors occurred
[2024-05-19 13:31:48] Closed the Error Log File




[2024-05-19 13:31:50] 


[2024-05-19 13:31:50] Started the Error Log File
[2024-05-19 13:32:32] No errors occurred
[2024-05-19 13:32:32] Closed the Error Log File




[2024-05-19 13:38:01] 


[2024-05-19 13:38:01] Started the Error Log File
[2024-05-19 13:40:24] No errors occurred
[2024-05-19 13:40:24] Closed the Error Log File




[2024-05-19 13:40:26] 


[2024-05-19 13:40:26] Started the Error Log File
[2024-05-19 13:40:31] No errors occurred
[2024-05-19 13:40:31] Closed the Error Log File




[2024-05-19 13:40:49] 


[2024-05-19 13:40:49] Started the Error Log File
[2024-05-19 13:41:29] No errors occurred
[2024-05-19 13:41:29] Closed the Error Log File




[2024-05-19 13:41:33] 


[2024-05-19 13:41:33] Started the Error Log File
[2024-05-19 13:42:38] No errors occurred
[2024-05-19 13:42:38] Closed the Error Log File




[2024-05-19 13:42:41] 


[2024-05-19 13:42:41] Started the Error Log File
[2024-05-19 13:43:05] No errors occurred
[2024-05-19 13:43:05] Closed the Error Log File




[2024-05-19 13:43:08] 


[2024-05-19 13:43:08] Started the Error Log File
[2024-05-19 13:43:34] No errors occurred
[2024-05-19 13:43:34] Closed the Error Log File




[2024-05-19 13:43:39] 


[2024-05-19 13:43:39] Started the Error Log File
[2024-05-19 13:44:18] No errors occurred
[2024-05-19 13:44:18] Closed the Error Log File




[2024-05-19 13:44:20] 


[2024-05-19 13:44:20] Started the Error Log File
[2024-05-19 13:44:51] No errors occurred
[2024-05-19 13:44:51] Closed the Error Log File




[2024-05-19 13:44:55] 


[2024-05-19 13:44:55] Started the Error Log File
[2024-05-19 13:45:02] No errors occurred
[2024-05-19 13:45:02] Closed the Error Log File




[2024-05-19 13:45:06] 


[2024-05-19 13:45:06] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 805, in get
    value = d[option]
            ~^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py", line 1006, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py", line 998, in __missing__
    raise KeyError(key)
KeyError: 'exitgame'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 82, in classic_snake_command
    self.functions['classic_snake']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 196, in classic_snake
    self.start_game("classic_snake")
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 258, in start_game
    self.classic_snake_canvas = SnakeClassicGame(self.root, self.game_config, self.game_logger, self.functions, self.create_button_panel) # pylint: disable=line-too-long
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_classic_game.py", line 97, in __init__
    self.configfile()
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_classic_game.py", line 165, in configfile
    'ExitGame': self.config.get('KeyBindings', 'ExitGame').split(', ')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 808, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'exitgame' in section: 'KeyBindings'
[2024-05-19 14:04:50] No errors occurred
[2024-05-19 14:04:50] Closed the Error Log File




[2024-05-19 14:06:06] 


[2024-05-19 14:06:06] Started the Error Log File
[2024-05-19 14:06:46] No errors occurred
[2024-05-19 14:06:46] Closed the Error Log File




[2024-05-19 14:20:39] 


[2024-05-19 14:20:39] Started the Error Log File
[2024-05-19 14:20:58] No errors occurred
[2024-05-19 14:20:58] Closed the Error Log File




[2024-05-19 14:22:22] 


[2024-05-19 14:22:22] Started the Error Log File
[2024-05-19 14:22:38] No errors occurred
[2024-05-19 14:22:38] Closed the Error Log File




[2024-05-19 14:23:36] 


[2024-05-19 14:23:36] Started the Error Log File
[2024-05-19 14:24:15] No errors occurred
[2024-05-19 14:24:15] Closed the Error Log File




[2024-05-19 14:33:58] 


[2024-05-19 14:33:58] Started the Error Log File
[2024-05-19 14:34:31] No errors occurred
[2024-05-19 14:34:31] Closed the Error Log File




